### ISSUE TITLE
Centrifuge: Incorrect displaying of token amount

### ISSUE THREAD

**Issue by ImdioR** [dappforce/dappforce-subsocial#16]
Good evening
This is Centrifuge Ambassador. I noticed that sub.id shows incorrect information about tokens amount.
Please note that after migration from stand-alone chain to Polkadot our old chain was switched off.
Feel free to contact for additional info.
Thank you in advance for the fast fix.
Best regards, Centrifuge.

**Comment by olehmell** [comment]
Hello. Thanks! We have fixed it

**Comment by ImdioR** [comment]
Awesome news! Thank you!!
