### ISSUE TITLE
Polkadot crowdloans and Kusama crowdloans data stopped loading

### ISSUE THREAD

**Issue by ImdioR** [dappforce/dappforce-subsocial#22]
Good day!

Unfortunately, i noticed, that Polkadot crowdloans and Kusama crowdloans part stopped loading this data a couple of days ago on Sub.id.
![image](https://user-images.githubusercontent.com/90972248/193820531-32507f76-34ae-4cec-a9ba-14c63ad35150.png)

Will be great if you fix this asap.
Thank you
Best regards.

**Comment by siman** [comment]
Should be fixed by now

**Comment by ImdioR** [comment]
Yes, thank you.

**Comment by ImdioR** [comment]
Hey there!
Just found that Polkadot crowdloans still can not load
